url: "https://www.truetourism.fr"
baseurl: ""
source: "."
destination: "./_site"

data_dir: _data

include:
  - .well-known
  - sitemap.xml
exclude:
  - .idea/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - readme.md
plugins:
  - jekyll-polyglot
  - jekyll-seo-tag

collections:
  guide:
    permalink: /:collection/:b64uuid

# Seo
title: "True Tourism"
tagline: "La bonne façon de visiter"
description: "True Tourism est une plateforme de réservation de visites guidées et d'activités touristiques en ligne. Nous proposons des visites guidées, des activités et des expériences uniques dans le monde entier. Réservez directement auprès des guides locaux et des agences de voyage."
image: "/assets/illustration_mobile.png"

# Polyglot
default_lang: 'fr'
languages: ['fr', 'en', 'es']
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "-"
# Custom variables
languages_aliases:
  fr: français
  en: english
  es: español
exclude_from_localization: [
  '.well-known',
  'assets',
  'css',
  'dist',
  'js',
  'node_modules',
  '_test',
  '.gitignore',
  '.ruby-version',
  '_config.yml',
  'app.html',
  'CNAME',
  'favicon.ico',
  'Gemfile',
  'Gemfile.lock',
  'guide.html',
  'package.json',
  'package-lock.json',
  'readme.md',
  'store.html',
  'tailwind.config.js',
]
parallel_localization: true


