url: "https://www.truetourism.fr"
baseurl: ""
source: "."
destination: "./_site"

data_dir: _data

include:
  - .well-known
  - sitemap.xml
exclude:
  - .idea/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - readme.md
plugins:
  - jekyll-polyglot
  - jekyll-seo-tag

collections:
  guides:
    output: true
  posts:
    output: true
    permalink: /:collection/:title

# Seo
title: "True Tourism"
tagline: "La bonne façon de visiter"
description: "Découvrez Marseille avec True Tourism: des visites guidées authentiques par des guides locaux passionnés. Explorez, savourez, et vivez l'expérience locale."
image: "/assets/illustration_mobile.png"

# Polyglot
default_lang: 'fr'
languages: ['fr', 'en', 'es']
# practical values langsep are "|", "•", "·", "-", "–"
langsep: "-"
# Custom variables
languages_aliases:
  fr: français
  en: english
  es: español
exclude_from_localization: [
  '.well-known',
  'assets',
  'css',
  'dist',
  'js',
  'node_modules',
  '_test',
  '.gitignore',
  '.ruby-version',
  '_config.yml',
  'app.html',
  'CNAME',
  'favicon.ico',
  'Gemfile',
  'Gemfile.lock',
  'guide.md',
  'package.json',
  'package-lock.json',
  'readme.md',
  'store.html',
  'tailwind.config.js',
]
parallel_localization: true


